spring:

  datasource:
    url: jdbc:mysql://localhost:3306/media?useSSL=false&user=root&password=password

  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
